### ISSUE TITLE
YouTube.com Issues

### ISSUE THREAD

**Issue by depleur** [safak45xx/Blurfox#15]
I've noticed a few bugs on YouTube.com recently.

1. The YouTube logo, the search logo (magnifying glass), and other black-coloured elements on the page (notifications, captions, etc.) seem broken in theatre mode. Shown below:
 ![CleanShot 2024-03-14 at 13 08 42@2x](https://github.com/safak45xx/Blurfox-MacOS-/assets/89105989/47eadb63-2a07-44c7-a254-5431b1f16525)
![CleanShot 2024-03-14 at 13 14 20@2x](https://github.com/safak45xx/Blurfox-MacOS-/assets/89105989/13dc6424-5839-41f5-b03c-e5a057d4e5cf)

2. Hovering over the Next button near the video timeline shows a weird picture of the thumbnail of the next video. Shown in the screenshot below:

 ![CleanShot 2024-03-14 at 13 11 33@2x](https://github.com/safak45xx/Blurfox-MacOS-/assets/89105989/ca7dbd13-8b8b-4d79-824d-4bdef5dd8bb1)

Hope these issues are of some help, and can be resolved in a future release!

**Comment by safak45xx** [comment]
Yes, it's solvable. All of them will be resolved in version 0.7.0.

**Comment by safak45xx** [comment]
If you see any more errors, please report them.

**Comment by safak45xx** [comment]
Does the CPU get heavily taxed when using custom websites?

**Comment by safak45xx** [comment]
![Ekran Resmi 2024-03-14 20 49 32](https://github.com/safak45xx/Blurfox-MacOS-/assets/141409983/12984f8c-59a8-4b5d-ac9d-66479e5e89b3)

From sites with added blur effect.

**Comment by safak45xx** [comment]
Please, since I haven't received this kind of feedback from other users, I'm not entirely sure about its usability.

**Comment by depleur** [comment]
Okay, so I ran a very preliminary test; I went to the Network section of the Inspect tab and this is what I found using the analyser:

Using Blurfox:

<img width="1599" alt="CleanShot 2024-03-15 at 01 37 55@2x" src="https://github.com/safak45xx/Blurfox-MacOS-/assets/89105989/753fa482-ba8e-4974-bd48-64c0eb351c16"><br>

Without using BlurFox:

<img width="1602" alt="CleanShot 2024-03-15 at 01 39 49@2x" src="https://github.com/safak45xx/Blurfox-MacOS-/assets/89105989/111f8286-39fc-431c-80c0-c21661be7e46">

Surprisingly, the cache loading time was faster using BlurFox, not sure why. I disabled all addon usage in both cases. Hopefully, this helps.

**Comment by safak45xx** [comment]
https://github.com/safak45xx/Blurfox-MacOS-/releases/tag/0.7.0 solved

**Comment by safak45xx** [comment]
I have a small request from you. Could you test all the sites with the blur effect as you did above? If you do, please open a new topic and share it there. I'm thinking of pinning this.

**Comment by safak45xx** [comment]
Currently active websites

-Github -Facebook -Youtube -Google -Duckduckgo

**Comment by depleur** [comment]
I can do that! I'll do that and make a new issue soon.

**Comment by depleur** [comment]
![CleanShot 2024-03-24 at 00 30 33@2x](https://github.com/safak45xx/Blurfox/assets/89105989/b6cfd84c-0766-4cf0-89a0-e27353600eeb)

Sorry for being a little inactive. I found this small bug in 0.9.0 on GitHub. The line that follows threads goes into every post as visible.

**Comment by safak45xx** [comment]
> ![CleanShot 2024-03-24 at 00 30 33@2x](https://private-user-images.githubusercontent.com/89105989/316263553-b6cfd84c-0766-4cf0-89a0-e27353600eeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTk3MTUsIm5iZiI6MTcxMTQ1OTQxNSwicGF0aCI6Ii84OTEwNTk4OS8zMTYyNjM1NTMtYjZjZmQ4NGMtMDc2Ni00Y2YwLTg5YTAtZTI3MzUzNjAwZWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEzMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTM2NzhhN2E4Njk5NTZlNmEyYTViZTUwZjMwZDYyMWNiNDg2MDE0ZGQ4ZjNiMjhkZmQxZmEwZjMyNDE5OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-PLp12gPjwFhe7DGmNKVt5678lEtPAyd5GAmj0B7CEs)
> 
> Sorry for being a little inactive. I found this small bug in 0.9.0 on GitHub. The line that follows threads goes into every post as visible.

Sure, wait for the full version
