### ISSUE TITLE
Slight Border Issue

### ISSUE THREAD

**Issue by depleur** [safak45xx/Blurfox#21]
![CleanShot 2024-03-31 at 19 22 20@2x](https://github.com/safak45xx/Blurfox/assets/89105989/b4c50cd1-f914-4437-b0c0-2a398fc720e9)

There is a slight issue with the top border of the transparent extentions pane (not uniform with side borders). Small bug I noticed.

**Comment by safak45xx** [comment]
Wait for the full version.
