### ISSUE TITLE
Address bar and new tab 

### ISSUE THREAD

**Issue by manuel-barbosaa** [safak45xx/Blurfox#23]
Address bar and first tab overlapping, can't find a solution to this unfortunately :/

![Screenshot 2024-04-08 110149](https://github.com/safak45xx/Blurfox/assets/126287678/b3c90757-321b-4b86-be39-9edef9ff2cf9)

**Comment by safak45xx** [comment]
![Ekran Resmi 2024-04-08 19 39 42](https://github.com/safak45xx/Blurfox/assets/141409983/ef10476d-bf26-487e-b48e-dd81ab22e671)

**Comment by safak45xx** [comment]
Customize toolbar > Remove the gap between the URL bar and the tabs

**Comment by safak45xx** [comment]
https://github.com/safak45xx/Blurfox/assets/141409983/09b611be-79bf-4afe-8b24-099aab3dc485
